version: '3.8'

networks:
    budget:
      external: true

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "4000:4000"
        volumes:
            - /app/node_modules
            - .:/app
        env_file: .env
        environment: 
            - CHOKIDAR_USEPOLLING=true
        networks: 
            - budget
    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - .:/app
        env_file: .env
        command: ["npm","run","watchtest"]
        networks: 
            - budget
